import {test,expect} from '@playwright/test';
test('family recipe variations, forbidden rules, meals, shopping and stories',async({page})=>{
 const recipes:any[]=[],meals:any[]=[],stories:any[]=[];let bought=false;
 await page.route('**/api/v1/profile/preferences',r=>r.fulfill({json:{language:'en'}}));
 await page.route('**/api/v1/advent/calendars**',r=>{const path=new URL(r.request().url()).pathname,method=r.request().method();let body:any=[];
 if(path.endsWith('/calendars'))body=[{id:'one',name:'Family Christmas',year:2026,timezone:'UTC',role:'OWNER'}];
 else if(path.endsWith('/occasions'))body=[{key:'day-0',title:'Thanksgiving',date:'2026-11-26'}];
 else if(path.endsWith('/recipes')){if(method==='POST'){const data=r.request().postDataJSON();const id=`r${recipes.length+1}`;recipes.push({...data,id,version:1,contributor:'Alex',canEdit:true});body={id};}else body=recipes;}
 else if(path.endsWith('/stories')){if(method==='POST')stories.push({id:'s1',author:'Alex',body:r.request().postDataJSON().body,createdAt:'2026-11-26',canRemove:true});body=stories;}
 else if(path.endsWith('/meals')){if(method==='POST'){const data=r.request().postDataJSON();meals.push({...data,id:'m1',version:1});body={id:'m1'};}else body=meals;}
 else if(path.endsWith('/shopping')){if(method==='PUT')bought=r.request().postDataJSON().checked;body=[{key:'potatoes',name:'Potatoes',unit:'kg',quantity:2,note:'',recipes:['Family potatoes'],checked:bought}];}
 return r.fulfill({json:body});});
 await page.goto('/');await page.getByRole('button',{name:'Recipes & meal plans',exact:true}).click();await page.getByRole('button',{name:'Add family recipe',exact:true}).click();
 await page.getByLabel('Recipe name',{exact:true}).fill('Family potatoes');await page.getByLabel('Recipe serves',{exact:true}).fill('4');await page.getByLabel('Quantity 1',{exact:true}).fill('1');await page.getByRole('combobox',{name:'Unit 1',exact:true}).selectOption('kg');await page.getByLabel('Ingredient 1',{exact:true}).fill('Potatoes');await page.getByLabel('Instructions',{exact:true}).fill('Prepare using our family method.');await page.getByLabel('Absolutely forbidden',{exact:true}).fill('No raisins in the potato salad.');await page.getByLabel('The story behind this recipe',{exact:true}).fill('A recipe we save for the holidays.');await page.getByRole('button',{name:'Save recipe',exact:true}).click();
 await expect(page.getByText('No raisins in the potato salad.',{exact:true})).toBeVisible();
 await page.getByLabel('Your recipe story',{exact:true}).fill('We always made this together.');await page.getByRole('button',{name:'Share recipe story',exact:true}).click();await expect(page.getByText('We always made this together.',{exact:true})).toBeVisible();
 await page.getByRole('button',{name:'Make a variation',exact:true}).click();await page.getByLabel('Recipe name',{exact:true}).fill('Our variation');await page.getByLabel('Variations and substitutions',{exact:true}).fill('Use our preferred seasoning.');await page.getByRole('button',{name:'Save recipe',exact:true}).click();await expect(page.getByRole('heading',{name:'Our variation',exact:true})).toBeVisible();expect(recipes[1].parentId).toBe('r1');expect(recipes[0].title).toBe('Family potatoes');
 await page.getByRole('button',{name:'Meal plans',exact:true}).click();await page.getByRole('button',{name:'Plan a meal',exact:true}).click();await page.getByLabel('Meal name',{exact:true}).fill('Thanksgiving dinner');await page.getByLabel('Guests',{exact:true}).fill('8');await page.getByRole('combobox',{name:'Add a recipe to the meal',exact:true}).selectOption('r1');await page.getByLabel('Who brings dish 1?',{exact:true}).fill('Sam');await page.getByRole('button',{name:'Save meal plan',exact:true}).click();await expect(page.getByRole('heading',{name:'Thanksgiving dinner',exact:true})).toBeVisible();expect(meals[0].dishes[0]).toEqual({recipeId:'r1',servings:8,bringer:'Sam'});
 await page.getByRole('button',{name:'View this meal’s shopping list',exact:true}).click();await expect(page.getByText('2 kg Potatoes',{exact:true})).toBeVisible();await page.getByRole('checkbox',{name:/2 kg Potatoes/}).check();await expect(page.getByRole('checkbox',{name:/2 kg Potatoes/})).toBeChecked();
 await page.setViewportSize({width:390,height:844});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);
});
