"use client";
import {useEffect,useState} from "react";
import type {API} from "./FamilyKitchen";
import {personalAPI} from './RecipeNutrition';
type Recipe={id:string;title:string;forbidden:string;servings:number};
type Meal={id:string;title:string;guests:number;notes:string;itemKey:string;dishes:{recipeId:string;servings:number;bringer:string;volunteeredByMe?:boolean}[]};
export function VolunteerButton({calendarId,mealId,dish,api,onSaved}:{calendarId:string;mealId:string;dish:Meal['dishes'][number];api:API;onSaved:()=>Promise<void>}){
 const [busy,setBusy]=useState(false),[error,setError]=useState('');
 if(dish.bringer&&!dish.volunteeredByMe)return null;
 return <><button type="button" disabled={busy} onClick={async()=>{setBusy(true);setError('');try{await api(`/${calendarId}/kitchen/meals/${mealId}/dishes/${dish.recipeId}/volunteer`,'PUT',{bringing:!dish.volunteeredByMe});await onSaved();}catch(e){setError((e as Error).message);await onSaved().catch(()=>{});}finally{setBusy(false);}}}>{busy?'Saving…':dish.volunteeredByMe?'Withdraw my offer':'I’ll bring this'}</button>{error&&<p role="alert">{error}</p>}</>;
}
export function DayMeals({calendarId,item,api}:{calendarId:string;item:string;api:API}){
 const [meals,setMeals]=useState<Meal[]>([]),[recipes,setRecipes]=useState<Recipe[]>([]),[personal,setPersonal]=useState<Recipe[]>([]),[error,setError]=useState(''),[notice,setNotice]=useState(''),[adding,setAdding]=useState(false),[busy,setBusy]=useState(true),[choice,setChoice]=useState(''),[mealId,setMealId]=useState(''),[servings,setServings]=useState(6);
 async function load(){const [m,r]=await Promise.all([api<Meal[]>(`/${calendarId}/kitchen/meals`),api<Recipe[]>(`/${calendarId}/kitchen/recipes`)]);setMeals(m.filter(v=>v.itemKey===item));setRecipes(r);}
 useEffect(()=>{let active=true;setAdding(false);setError('');setNotice('');setChoice('');setMealId('');setBusy(true);Promise.all([api<Meal[]>(`/${calendarId}/kitchen/meals`),api<Recipe[]>(`/${calendarId}/kitchen/recipes`)]).then(([m,r])=>{if(active){const today=m.filter(v=>v.itemKey===item);setMeals(today);setMealId(today[0]?.id||'');setRecipes(r);}}).catch(e=>{if(active)setError(e.message);}).finally(()=>{if(active)setBusy(false);});return()=>{active=false;};},[calendarId,item]);
 return <section className="day-meals"><h3>At our table today</h3>{error&&<p role="alert">{error}</p>}{notice&&<p role="status">{notice}</p>}<button disabled={busy} onClick={async()=>{setAdding(true);setError('');try{setPersonal(await personalAPI<Recipe[]>('/recipes'));}catch{setError('Personal recipes could not be loaded. You can still choose a calendar recipe.');}}}>Add a dish to this day</button>
 {adding&&<form onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');try{const [source,id]=choice.split(':');await api(`/${calendarId}/kitchen/dishes`,'POST',{itemKey:item,mealId,recipeId:source==='calendar'?id:'',personalRecipeId:source==='personal'?id:'',servings});await load();setAdding(false);setNotice('Dish added. Choose “I’ll bring this” to volunteer.');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}}><fieldset disabled={busy}><label>Meal for this dish<select value={mealId} onChange={e=>setMealId(e.target.value)}><option value="">New shared meal for this day</option>{meals.map(m=><option value={m.id} key={m.id}>{m.title}</option>)}</select></label><label>Dish to add<select required value={choice} onChange={e=>{setChoice(e.target.value);const [source,id]=e.target.value.split(':');setServings((source==='personal'?personal:recipes).find(r=>r.id===id)?.servings||6);}}><option value="">Choose a recipe</option><optgroup label="This calendar">{recipes.map(r=><option key={r.id} value={`calendar:${r.id}`}>{r.title}</option>)}</optgroup><optgroup label="My personal recipes · shares a copy">{personal.map(r=><option key={r.id} value={`personal:${r.id}`}>{r.title}</option>)}</optgroup></select></label><label>Servings to bring<input required type="number" min={1} max={200} value={servings} onChange={e=>setServings(Number(e.target.value))}/></label><p className="fine">Personal recipes are copied into this calendar for everyone to see. <a href="/profile/recipes">Manage my recipes</a></p><button className="primary">Add dish</button><button type="button" onClick={()=>setAdding(false)}>Cancel dish</button></fieldset></form>}
 {!busy&&!meals.length&&<p>No dishes planned for this day yet.</p>}{meals.map(m=><article key={m.id}><h4>{m.title} · {m.guests} guests</h4><p className="message">{m.notes}</p><ul>{m.dishes.map(d=>{const r=recipes.find(r=>r.id===d.recipeId);return <li key={d.recipeId}><p>{r?.title} · {d.servings} servings · {d.bringer||'Not assigned'}</p><VolunteerButton calendarId={calendarId} mealId={m.id} dish={d} api={api} onSaved={load}/>{r?.forbidden&&<p><strong>Absolutely forbidden:</strong> {r.forbidden}</p>}</li>;})}</ul></article>)}<p className="fine">Open Recipes & meal plans from the calendar for the full recipes and shopping list.</p></section>;
}
