"use client";
import {useEffect,useState} from "react";
import {VolunteerButton} from "./DayMeals";
import ArtworkUpload from "./ArtworkUpload";
import {ArtworkPicker,type Artwork} from "./TraditionPlanner";
export type API=<T>(path:string,method?:string,body?:unknown)=>Promise<T>;
import {IngredientNutrition,NutritionFacts,DietaryOptions,personalAPI,type Ingredient} from './RecipeNutrition';
import {SharePersonal,PersonalRecipePicker} from './LibrarySharing';
type Recipe={id:string;parentId:string;contributor:string;title:string;servings:number;ingredients:Ingredient[];instructions:string;variations:string;dietary:string;forbidden:string;story:string;artworkId:string;image?:Artwork;version:number;canEdit:boolean};
type Dish={recipeId:string;servings:number;bringer:string;volunteeredByMe?:boolean};
type Meal={id:string;title:string;itemKey:string;guests:number;notes:string;dishes:Dish[];version:number};
type Occasion={key:string;title:string;date:string};
type Story={id:string;author:string;body:string;createdAt:string;canRemove:boolean};
type Shopping={key:string;name:string;unit:string;quantity:number|null;note:string;recipes:string[];checked:boolean};
const units=[['','No unit'],['each','each'],['g','g'],['kg','kg'],['ml','ml'],['l','L'],['tsp','tsp'],['tbsp','tbsp'],['cup','cup'],['oz','oz'],['lb','lb'],['pinch','pinch'],['can','can'],['package','package']];
const blankIngredient=():Ingredient=>({quantity:null,unit:"",name:"",note:""});
const emptyRecipe=():Recipe=>({id:"",parentId:"",contributor:"",title:"",servings:6,ingredients:[blankIngredient()],instructions:"",variations:"",dietary:"",forbidden:"",story:"",artworkId:"",version:0,canEdit:true});
export default function FamilyKitchen({calendarId,canPlan,api,onClose,initialItem="",personal=false}:{calendarId:string;canPlan:boolean;api:API;onClose:()=>void;initialItem?:string;personal?:boolean}){
 const path=personal?"":`/${calendarId}/kitchen`;
 const [recipes,setRecipes]=useState<Recipe[]>([]),[meals,setMeals]=useState<Meal[]>([]),[occasions,setOccasions]=useState<Occasion[]>([]),[art,setArt]=useState<Artwork[]>([]);
 const [tab,setTab]=useState(initialItem?"meals":"recipes"),[selected,setSelected]=useState(""),[edit,setEdit]=useState<Recipe|null>(null),[mealEdit,setMealEdit]=useState<Meal|null>(null),[mealId,setMealId]=useState("");
 const [search,setSearch]=useState(""),[busy,setBusy]=useState(true),[error,setError]=useState(""),[notice,setNotice]=useState(""),[stories,setStories]=useState<Story[]>([]),[shopping,setShopping]=useState<Shopping[]>([]),[story,setStory]=useState(""),[reportReason,setReportReason]=useState("");
 const recipe=recipes.find(r=>r.id===selected),meal=meals.find(m=>m.id===mealId);
 async function load(){const [rs,ms,os]=await Promise.all([api<Recipe[]>(`${path}/recipes`),api<Meal[]>(`${path}/meals`),api<Occasion[]>(`${path}/occasions`)]);setRecipes(rs);setMeals(ms);setOccasions(os);return {rs,ms};}
 useEffect(()=>{let active=true;Promise.all([api<Recipe[]>(`${path}/recipes`),api<Meal[]>(`${path}/meals`),api<Occasion[]>(`${path}/occasions`),canPlan&&!personal?api<Artwork[]>(`/${calendarId}/artwork`):Promise.resolve([])]).then(([rs,ms,os,images])=>{if(active){setRecipes(rs);setMeals(ms);setOccasions(os);setArt(images);setSelected(rs[0]?.id||"");setMealId(ms.find(m=>m.itemKey===initialItem)?.id||ms[0]?.id||"");}}).catch(e=>{if(active)setError(e.message);}).finally(()=>{if(active)setBusy(false);});return()=>{active=false;};},[path,canPlan,initialItem]);
 useEffect(()=>{let active=true;setStories([]);setStory("");if(selected&&!personal)api<Story[]>(`${path}/recipes/${selected}/stories`).then(s=>{if(active)setStories(s);}).catch(e=>{if(active)setError(e.message);});return()=>{active=false;};},[path,selected]);
 useEffect(()=>{let active=true;setShopping([]);if(mealId)api<Shopping[]>(`${path}/meals/${mealId}/shopping`).then(s=>{if(active)setShopping(s);}).catch(e=>{if(active)setError(e.message);});return()=>{active=false;};},[path,mealId,meals,recipes]);
 async function run(fn:()=>Promise<void>){setBusy(true);setError("");setNotice("");try{await fn();}catch(e){setError(e instanceof Error?e.message:"Please retry.");}finally{setBusy(false);}}
 function ingredient(index:number,patch:Partial<Ingredient>){if(edit)setEdit({...edit,ingredients:edit.ingredients.map((i,n)=>n===index?{...i,...patch}:i)});}
 function newMeal(){setMealEdit({id:"",title:"",itemKey:initialItem||occasions.find(o=>o.key==="day-0")?.key||occasions[0]?.key||"",guests:6,notes:"",dishes:[],version:0});}
 const occasion=(key:string)=>occasions.find(o=>o.key===key);
 return <section className="panel family-kitchen"><div className="page-heading"><div><p className="eyebrow">Recipes worth keeping. People worth gathering.</p><h2>{personal?"My recipes & meals":"Our family table"}</h2></div><button onClick={onClose}>Close recipe book</button></div>
 <p>{personal?"Your private recipe library belongs to your account. Keep dishes, variations and meal plans here, then choose which calendars receive a copy.":"Keep the original, make a variation, and tell the story behind it. This book is private to your calendar. Reusing your saved calendar plan copies the recipes and stories; each year’s meals and shopping list start fresh."}</p>
 <div className="toolbar" role="group" aria-label="Recipe book sections">{[['recipes','Family recipes'],['meals','Meal plans'],['shopping','Shopping list']].map(([key,label])=><button key={key} aria-pressed={tab===key} onClick={()=>{setTab(key);setEdit(null);setMealEdit(null);}}>{label}</button>)}</div>
 {error&&<p role="alert" className="error">{error} <button disabled={busy} onClick={()=>void run(async()=>{await load();setEdit(null);setMealEdit(null);})}>Reload recipe book</button></p>}{notice&&<p role="status">{notice}</p>}{busy&&<p role="status">Saving or loading your family table…</p>}
 {tab==="recipes"&&<>{!personal&&<PersonalRecipePicker calendarId={calendarId} onAdded={async()=>{await load();}}/>}<div className="toolbar"><label>Find a recipe<input type="search" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Name, contributor, or dietary note"/></label><button disabled={busy} onClick={()=>setEdit(emptyRecipe())}>Add family recipe</button></div>
 {!recipes.length&&!busy&&<p>No recipes yet. Add a family favorite—including the things that must absolutely never go in it.</p>}
 {recipes.length>0&&<label>Recipe<select value={selected} disabled={busy} onChange={e=>{setSelected(e.target.value);setEdit(null);}}><option value="">Choose a recipe</option>{recipes.filter(r=>r.id===selected||`${r.title} ${r.contributor} ${r.dietary}`.toLowerCase().includes(search.toLowerCase())).map(r=><option key={r.id} value={r.id}>{r.title}{r.parentId?" · variation":""} · {r.contributor}</option>)}</select></label>}
 {edit?<form onSubmit={e=>{e.preventDefault();void run(async()=>{const saved=await api<{id:string}>(`${path}/recipes${edit.id?`/${edit.id}`:""}`,edit.id?"PUT":"POST",edit);await load();setSelected(saved.id);setEdit(null);setNotice("Recipe saved in your family book.");});}}><fieldset disabled={busy}>
 <h3>{edit.id?"Edit recipe":edit.parentId?"Your variation":"A new family recipe"}</h3>
 <div className="form-grid"><label>Recipe name<input required maxLength={160} value={edit.title} onChange={e=>setEdit({...edit,title:e.target.value})}/></label><label>Recipe serves<input type="number" required min={1} max={200} value={edit.servings} onChange={e=>setEdit({...edit,servings:Number(e.target.value)})}/></label></div>
 <h4>Ingredients</h4><p className="fine">Use decimal quantities (0.5 for ½). Leave quantity blank for “to taste.” Shopping totals keep different units and preparation notes separate.</p>
 {edit.ingredients.map((i,index)=><div className="ingredient-editor" key={index}><div className="ingredient-row"><label>Quantity {index+1}<input type="number" min="0.0001" max="10000" step="0.0001" value={i.quantity??""} onChange={e=>ingredient(index,{quantity:e.target.value===""?null:Number(e.target.value)})}/></label><label>Unit {index+1}<select value={i.unit} onChange={e=>ingredient(index,{unit:e.target.value,nutrition:null})}>{units.map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></label><label>Ingredient {index+1}<input required maxLength={120} value={i.name} onChange={e=>ingredient(index,{name:e.target.value,nutrition:null})}/></label><label>Preparation note {index+1}<input maxLength={200} value={i.note} onChange={e=>ingredient(index,{note:e.target.value})} placeholder="Chopped, unsalted…"/></label><button type="button" disabled={edit.ingredients.length===1} onClick={()=>setEdit({...edit,ingredients:edit.ingredients.filter((_,n)=>n!==index)})}>Remove ingredient {index+1}</button></div><IngredientNutrition ingredient={i} index={index} onChange={nutrition=>ingredient(index,{nutrition})}/></div>)}
 <button type="button" disabled={edit.ingredients.length>=80} onClick={()=>setEdit({...edit,ingredients:[...edit.ingredients,blankIngredient()]})}>Add ingredient</button>
 <label>Instructions<textarea required rows={6} maxLength={12000} value={edit.instructions} onChange={e=>setEdit({...edit,instructions:e.target.value})}/></label>
 <label>Variations and substitutions<textarea rows={3} maxLength={2000} value={edit.variations} onChange={e=>setEdit({...edit,variations:e.target.value})}/></label>
 <DietaryOptions value={edit.dietary} onChange={dietary=>setEdit({...edit,dietary})}/><label>Dietary needs and ingredient notes<textarea rows={2} maxLength={1000} value={edit.dietary} onChange={e=>setEdit({...edit,dietary:e.target.value})}/></label>
 <label className="forbidden">Absolutely forbidden<textarea rows={3} maxLength={2000} value={edit.forbidden} onChange={e=>setEdit({...edit,forbidden:e.target.value})} placeholder="No raisins in the potato salad. We mean it."/></label>
 <label>The story behind this recipe<textarea rows={4} maxLength={4000} value={edit.story} onChange={e=>setEdit({...edit,story:e.target.value})} placeholder="Who taught you? When do you make it? What makes it ours?"/></label>
 {canPlan&&!personal&&<><ArtworkUpload key={edit.id||edit.parentId||"new"} calendarId={calendarId} api={api} onUploaded={image=>{setArt(a=>[...a,image]);setEdit(current=>current?{...current,artworkId:image.id}:current);}}/><ArtworkPicker value={edit.artworkId} items={art} onChange={artworkId=>setEdit({...edit,artworkId})}/></>}
 <NutritionFacts ingredients={edit.ingredients} servings={edit.servings||1}/><div className="toolbar"><button className="primary">Save recipe</button><button type="button" onClick={()=>setEdit(null)}>Cancel recipe edits</button></div></fieldset></form>:recipe&&<article className="recipe-card"><div className="page-heading"><div><h3>{recipe.title}</h3><p>Contributed by {recipe.contributor} · Serves {recipe.servings}</p>{recipe.parentId&&<p>Variation of <button onClick={()=>setSelected(recipe.parentId)}>{recipes.find(r=>r.id===recipe.parentId)?.title||"the original recipe"}</button></p>}</div><div className="toolbar">{recipe.canEdit&&<button disabled={busy} onClick={()=>setEdit({...recipe,ingredients:recipe.ingredients.map(i=>({...i}))})}>Edit recipe</button>}<button disabled={busy} onClick={()=>setEdit({...recipe,id:"",parentId:recipe.id,title:`${recipe.title} · our variation`,version:0,ingredients:recipe.ingredients.map(i=>({...i}))})}>Make a variation</button></div></div>
 {recipe.image?.url&&<img className="advent-illustration" src={recipe.image.url} alt={recipe.image.alt} referrerPolicy="no-referrer"/>}
 {recipe.image?.uploaded&&<details><summary>Report this image</summary><form onSubmit={e=>{e.preventDefault();void run(async()=>{await api(`${path}/recipes/${recipe.id}/report-image`,"POST",{body:reportReason});await load();setReportReason("");setNotice("The reported image is hidden. Previously loaded copies may remain visible briefly.");});}}><label>Image concern<textarea required maxLength={500} value={reportReason} onChange={e=>setReportReason(e.target.value)}/></label><button disabled={busy}>Report and hide recipe image</button></form></details>}
 <h4>Ingredients</h4><ul>{recipe.ingredients.map((i,n)=><li key={n}>{i.quantity??"To taste"} {i.unit} {i.name}{i.note?` — ${i.note}`:""}</li>)}</ul><h4>Instructions</h4><p className="message">{recipe.instructions}</p>
 {recipe.variations&&<><h4>Variations and substitutions</h4><p className="message">{recipe.variations}</p></>}{recipe.dietary&&<><h4>Dietary notes</h4><p className="fine">Cook-entered preferences, not verified allergy or certification claims. Check labels and cross-contact; lactose-free does not mean milk-free.</p><p className="message">{recipe.dietary}</p></>}
 <NutritionFacts ingredients={recipe.ingredients} servings={recipe.servings}/><aside className="forbidden"><h4>Absolutely forbidden</h4><p className="message">{recipe.forbidden||"No family rules recorded yet."}</p></aside>
 {recipe.story&&<><h4>The story behind this recipe</h4><p className="message">{recipe.story}</p></>}
 {recipes.some(r=>r.parentId===recipe.id)&&<><h4>Family variations</h4><div className="toolbar">{recipes.filter(r=>r.parentId===recipe.id).map(r=><button key={r.id} onClick={()=>setSelected(r.id)}>{r.title}</button>)}</div></>}
 {personal?<SharePersonal id={recipe.id} kind="recipes"/>:<><button disabled={busy} onClick={()=>void run(async()=>{await personalAPI("/import","POST",{calendarId,recipeId:recipe.id});setNotice("A text and nutrition copy is saved in your personal library. Calendar photos and other people’s comments stay here.");})}>Save to my personal recipes</button><h4>Stories around the table</h4>{stories.map(s=><article className="memory" key={s.id}><strong>{s.author}</strong><p className="message">{s.body}</p>{s.canRemove&&<button disabled={busy} onClick={()=>void run(async()=>{await api(`${path}/recipes/${recipe.id}/stories/${s.id}`,"DELETE");setStories(await api<Story[]>(`${path}/recipes/${recipe.id}/stories`));})}>Remove story</button>}</article>)}
 <form onSubmit={e=>{e.preventDefault();void run(async()=>{await api(`${path}/recipes/${recipe.id}/stories`,"POST",{body:story});setStories(await api<Story[]>(`${path}/recipes/${recipe.id}/stories`));setStory("");setNotice("Your recipe story is shared.");});}}><label>Your recipe story<textarea required maxLength={2000} rows={3} value={story} onChange={e=>setStory(e.target.value)}/></label><button disabled={busy}>Share recipe story</button></form></>}
 </article>}</>}
 {tab!=="recipes"&&<><div className="toolbar"><label>Gathering meal<select value={mealId} disabled={busy} onChange={e=>{setMealId(e.target.value);setMealEdit(null);}}><option value="">Choose a meal</option>{meals.map(m=><option key={m.id} value={m.id}>{m.title} · {occasion(m.itemKey)?.date||"Date to be chosen"}</option>)}</select></label>{canPlan&&<button disabled={busy} onClick={()=>{setTab("meals");newMeal();}}>Plan a meal</button>}</div>{!meals.length&&!busy&&<p>No meals planned yet. {canPlan?"Choose a calendar day or gathering and add dishes from your recipe book.":"Your host or a co-editor can organize the menu."}</p>}</>}
 {tab==="meals"&&(mealEdit?<form onSubmit={e=>{e.preventDefault();void run(async()=>{const saved=await api<{id:string}>(`${path}/meals${mealEdit.id?`/${mealEdit.id}`:""}`,mealEdit.id?"PUT":"POST",mealEdit);await load();setMealId(saved.id);setMealEdit(null);setNotice("Meal plan saved. Shopping quantities have been recalculated.");});}}><fieldset disabled={busy}><h3>{mealEdit.id?"Edit meal":"Plan a gathering meal"}</h3><div className="form-grid"><label>Meal name<input required maxLength={160} value={mealEdit.title} onChange={e=>setMealEdit({...mealEdit,title:e.target.value})}/></label><label>Calendar day or gathering<select required value={mealEdit.itemKey} onChange={e=>setMealEdit({...mealEdit,itemKey:e.target.value})}>{occasions.map(o=><option key={o.key} value={o.key}>{o.title} · {o.date||"Date to be chosen"}</option>)}</select></label><label>Guests<input type="number" required min={1} max={200} value={mealEdit.guests} onChange={e=>setMealEdit({...mealEdit,guests:Number(e.target.value)})}/></label></div>
 <p className="fine">New dishes default to the guest count. Set each dish’s servings for your table. Changing guests does not silently change existing dish amounts.</p><button type="button" onClick={()=>setMealEdit({...mealEdit,dishes:mealEdit.dishes.map(d=>({...d,servings:mealEdit.guests}))})}>Use guest count for every dish</button>
 {mealEdit.dishes.map((d,index)=><div className="meal-dish" key={d.recipeId}><strong>{recipes.find(r=>r.id===d.recipeId)?.title}</strong><label>Servings for dish {index+1}<input type="number" min={1} max={200} required value={d.servings} onChange={e=>setMealEdit({...mealEdit,dishes:mealEdit.dishes.map((v,n)=>n===index?{...v,servings:Number(e.target.value)}:v)})}/></label><label>Who brings dish {index+1}?<input maxLength={80} value={d.bringer} onChange={e=>setMealEdit({...mealEdit,dishes:mealEdit.dishes.map((v,n)=>n===index?{...v,bringer:e.target.value}:v)})} placeholder="Name or unassigned"/></label><button type="button" onClick={()=>setMealEdit({...mealEdit,dishes:mealEdit.dishes.filter((_,n)=>n!==index)})}>Remove dish {index+1}</button></div>)}
 <label>Add a recipe to the meal<select value="" onChange={e=>{if(e.target.value)setMealEdit({...mealEdit,dishes:[...mealEdit.dishes,{recipeId:e.target.value,servings:mealEdit.guests,bringer:""}]});}}><option value="">Choose a recipe</option>{recipes.filter(r=>!mealEdit.dishes.some(d=>d.recipeId===r.id)).map(r=><option key={r.id} value={r.id}>{r.title}</option>)}</select></label>
 {!recipes.length&&<p>Add recipes in the Family recipes section first.</p>}<label>Meal notes<textarea maxLength={2000} rows={3} value={mealEdit.notes} onChange={e=>setMealEdit({...mealEdit,notes:e.target.value})}/></label><div className="toolbar"><button className="primary">Save meal plan</button><button type="button" onClick={()=>setMealEdit(null)}>Cancel meal edits</button></div></fieldset></form>:meal&&<article><h3>{meal.title}</h3><p>{occasion(meal.itemKey)?.title||"Gathering no longer included"} · {occasion(meal.itemKey)?.date||"Date to be chosen"} · {meal.guests} guests</p><p className="message">{meal.notes}</p>{canPlan&&<button disabled={busy} onClick={()=>setMealEdit({...meal,dishes:meal.dishes.map(d=>({...d}))})}>Edit meal plan</button>}
 {meal.dishes.map(d=>{const r=recipes.find(r=>r.id===d.recipeId);return <article className="meal-dish" key={d.recipeId}><button onClick={()=>{setSelected(d.recipeId);setTab("recipes");}}>{r?.title}</button><p>{d.servings} servings · {d.bringer||"Who’s bringing it? Not assigned yet."}</p>{!personal&&<VolunteerButton calendarId={calendarId} mealId={meal.id} dish={d} api={api} onSaved={async()=>{await load();}}/>}{r?.forbidden&&<p className="forbidden"><strong>Absolutely forbidden:</strong> {r.forbidden}</p>}</article>;})}<button onClick={()=>setTab("shopping")}>View this meal’s shopping list</button>{personal&&<SharePersonal id={meal.id} kind="meals"/>}</article>)}
 {tab==="shopping"&&meal&&<section><h3>Shopping for {meal.title}</h3><p>Scaled from each dish’s planned servings. Matching names, units and preparation notes are combined. “To taste” stays unmeasured. Checked items are shared with the calendar; changing the menu clears its checks.</p>{!shopping.length&&<p>Add dishes to this meal to build its shopping list.</p>}
 {shopping.map(i=><label className={`shopping-item ${i.checked?"bought":""}`} key={i.key}><input type="checkbox" checked={i.checked} disabled={busy} onChange={e=>{const checked=e.target.checked;setShopping(rows=>rows.map(row=>row.key===i.key?{...row,checked}:row));void run(async()=>{try{await api(`${path}/meals/${meal.id}/shopping`,"PUT",{key:i.key,checked});setShopping(await api<Shopping[]>(`${path}/meals/${meal.id}/shopping`));}catch(e){setShopping(rows=>rows.map(row=>row.key===i.key?{...row,checked:i.checked}:row));throw e;}});}}/><span><strong>{i.quantity??"To taste"} {i.unit} {i.name}</strong>{i.note&&<span> · {i.note}</span>}<small>For {i.recipes.join(", ")}</small></span></label>)}
 </section>}
 </section>;
}
