"use client";
import {useEffect,useState} from 'react';
import {personalAPI} from './RecipeNutrition';
type Calendar={id:string;name:string;year:number;role:string};
export function SharePersonal({id,kind}:{id:string;kind:'recipes'|'meals'}){const [calendars,setCalendars]=useState<Calendar[]>([]),[calendar,setCalendar]=useState(''),[occasions,setOccasions]=useState<{key:string;title:string;date:string}[]>([]),[item,setItem]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false);
useEffect(()=>{let active=true;fetch('/api/v1/advent/calendars',{cache:'no-store'}).then(async r=>{if(!r.ok)throw new Error('Calendars could not be loaded.');return r.json();}).then(cs=>{if(active)setCalendars(cs);}).catch(e=>{if(active)setNotice(e.message);});return()=>{active=false;};},[]);
useEffect(()=>{setItem('');setOccasions([]);setNotice('');if(!calendar||kind!=='meals')return;let active=true;fetch(`/api/v1/advent/calendars/${calendar}/kitchen/occasions`,{cache:'no-store'}).then(async r=>{if(!r.ok)throw new Error('Gatherings could not be loaded.');return r.json();}).then(os=>{if(active){setOccasions(os);setItem(os[0]?.key||'');}}).catch(e=>{if(active)setNotice(e.message);});return()=>{active=false;};},[calendar,kind,id]);
return <section className="panel"><h4>Add a copy to a calendar</h4><p>Your personal original stays private. The selected calendar receives the recipe, notes, story, dietary labels and nutrition. Later edits stay independent. {kind==='meals'&&'Organizing a calendar meal requires owner or co-editor access.'}</p><label>Share with calendar<select value={calendar} onChange={e=>setCalendar(e.target.value)}><option value="">Choose a calendar</option>{calendars.filter(c=>kind==='recipes'||c.role!=='MEMBER').map(c=><option key={c.id} value={c.id}>{c.name} · {c.year}</option>)}</select></label>{kind==='meals'&&<label>Gathering for shared meal<select value={item} onChange={e=>setItem(e.target.value)}>{occasions.map(o=><option key={o.key} value={o.key}>{o.title} · {o.date||'Date to be chosen'}</option>)}</select></label>}<button disabled={busy||!calendar||(kind==='meals'&&!item)} onClick={async()=>{setBusy(true);setNotice('');try{await personalAPI(`/${kind}/${id}/share`,'POST',{calendarId:calendar,itemKey:item});setNotice('Copy added to the calendar.');}catch(e){setNotice((e as Error).message);}finally{setBusy(false);}}}>Add {kind==='recipes'?'recipe':'meal and dishes'} to calendar</button>{notice&&<p role="status">{notice}</p>}</section>;}
export function PersonalRecipePicker({calendarId,onAdded}:{calendarId:string;onAdded:()=>Promise<void>}){const [recipes,setRecipes]=useState<{id:string;title:string}[]>([]),[selected,setSelected]=useState(''),[busy,setBusy]=useState(false),[notice,setNotice]=useState('');useEffect(()=>{let active=true;personalAPI<{id:string;title:string}[]>('/recipes').then(rs=>{if(active)setRecipes(rs);}).catch(e=>{if(active)setNotice(e.message);});return()=>{active=false;};},[]);return <details><summary>Add from my personal recipes</summary><p>A copy is shared with this calendar. <a href="/profile/recipes">Manage my personal recipes and meals</a></p><label>My saved recipe<select value={selected} onChange={e=>setSelected(e.target.value)}><option value="">Choose a personal recipe</option>{recipes.map(r=><option key={r.id} value={r.id}>{r.title}</option>)}</select></label><button disabled={!selected||busy} onClick={async()=>{setBusy(true);setNotice('');try{await personalAPI(`/recipes/${selected}/share`,'POST',{calendarId});await onAdded();setNotice('Personal recipe added to this calendar.');}catch(e){setNotice((e as Error).message);}finally{setBusy(false);}}}>Add selected recipe</button>{notice&&<p role="status">{notice}</p>}</details>;}
