"use client";
import {useEffect,useState} from "react";
export type CalendarEntry={key:string;date:string;label:string;state:string;opened?:boolean;open:()=>void};
export default function MonthDoors({year,entries,busy,language,calendarId}:{calendarId:string;year:number;entries:CalendarEntry[];busy:boolean;language:string}){
 const [mealDates,setMealDates]=useState<string[]>([]);
 useEffect(()=>{const controller=new AbortController();setMealDates([]);async function load(){try{const responses=await Promise.all(['meals','occasions'].map(path=>fetch(`/api/v1/advent/calendars/${calendarId}/kitchen/${path}`,{cache:'no-store',signal:controller.signal})));if(responses.some(r=>!r.ok))return;const [meals,occasions]=await Promise.all(responses.map(r=>r.json()));if(!controller.signal.aborted)setMealDates(meals.map((m:{itemKey:string})=>occasions.find((o:{key:string;date:string})=>o.key===m.itemKey)?.date).filter(Boolean));}catch{}}void load();return()=>controller.abort();},[calendarId]);
 const months=Array.from(new Set([`${year}-12`,...entries.filter(e=>e.date).map(e=>e.date.slice(0,7))])).sort();
 const weekdays=Array.from({length:7},(_,n)=>new Intl.DateTimeFormat(language,{weekday:'short',timeZone:'UTC'}).format(new Date(Date.UTC(2026,10,1+n))));
 return <div className="month-calendars">{months.map(month=>{const [y,m]=month.split('-').map(Number);const offset=new Date(Date.UTC(y,m-1,1)).getUTCDay();const days=new Date(Date.UTC(y,m,0)).getUTCDate();const heading=new Intl.DateTimeFormat(language,{month:'long',year:'numeric',timeZone:'UTC'}).format(new Date(Date.UTC(y,m-1,1)));
 return <section className="month-calendar" key={month} aria-label={heading}><h2>{heading}</h2><div className="month-weekdays" aria-hidden="true">{weekdays.map(w=><span key={w}>{w}</span>)}</div><div className="month-days">{Array.from({length:offset},(_,i)=><div key={`blank-${i}`} className="month-blank" aria-hidden="true"/>)}{Array.from({length:days},(_,i)=>{const day=i+1,date=`${month}-${String(day).padStart(2,'0')}`,items=entries.filter(e=>e.date===date);const full=new Intl.DateTimeFormat(language,{weekday:'long',month:'long',day:'numeric',year:'numeric',timeZone:'UTC'}).format(new Date(Date.UTC(y,m-1,day)));return <div className={`month-day week-${Math.floor((offset+i)/7)%2}`} key={date}><time dateTime={date} aria-label={full}>{day}</time>{items.map(e=><button key={e.key} className={`month-door ${e.opened?'opened':''}`} disabled={busy||e.state!=='AVAILABLE'} aria-label={`${full}: ${e.label||'Advent door'}: ${e.state==='AVAILABLE'?(e.opened?'read again':'open door'):e.state==='DRAFT'?'not ready':'not yet open'}`} onClick={e.open}><span>{e.label||'Open door'}</span><small>{e.state==='AVAILABLE'?(e.opened?'Opened':'Ready'):e.state==='DRAFT'?'Not ready':'Locked'}</small></button>)}{mealDates.includes(date)&&<span className="month-meal">Meal planned</span>}</div>;})}</div></section>;})}</div>;
}
