"use client";
import {useState} from "react";
export type Nutrition={source:string;gramsPerUnit:number|null;calories:number|null;protein:number|null;carbohydrates:number|null;fat:number|null;fiber:number|null;sugar:number|null;sodium:number|null};
export type Ingredient={quantity:number|null;unit:string;name:string;note:string;nutrition?:Nutrition|null};
export const nutrients=[['calories','Energy','kcal'],['protein','Protein','g'],['carbohydrates','Carbohydrates','g'],['fat','Fat','g'],['fiber','Fiber','g'],['sugar','Sugars','g'],['sodium','Sodium','mg']] as const;
export async function personalAPI<T>(path:string,method='GET',body?:unknown):Promise<T>{const r=await fetch(`/api/v1/profile/kitchen${path}`,{method,headers:{'Content-Type':'application/json'},body:body===undefined?undefined:JSON.stringify(body),cache:'no-store'});const data=await r.json();if(!r.ok)throw new Error(data.detail||data.error||'Your recipe library could not be loaded. Please retry.');return data;}
const mass:Record<string,number>={g:1,kg:1000,oz:28.349523125,lb:453.59237};
export function nutritionTotals(ingredients:Ingredient[],servings:number){return nutrients.map(([key,label,unit])=>{let total=0,missing=0;for(const i of ingredients){const weight=mass[i.unit]??i.nutrition?.gramsPerUnit;if(i.quantity==null||!weight||i.nutrition?.[key]==null){missing++;continue;}total+=i.quantity*weight*i.nutrition[key]!/100;}return {key,label,unit,missing,total,perServing:total/servings};});}
export function NutritionFacts({ingredients,servings}:{ingredients:Ingredient[];servings:number}){const rows=nutritionTotals(ingredients,servings);return <section className="nutrition-facts"><h4>Estimated nutrition · {servings} servings</h4><p className="fine">One serving is 1/{servings} of this recipe. Cooking yield and discarded oil or liquid can change these estimates. Missing information is not counted as zero.</p><table><thead><tr><th>Nutrient</th><th>Per serving</th><th>Whole recipe</th></tr></thead><tbody>{rows.map(r=><tr key={r.key}><th>{r.label} ({r.unit})</th><td>{r.missing?`Incomplete (${ingredients.length-r.missing}/${ingredients.length} ingredients)` :r.perServing.toLocaleString(undefined,{maximumFractionDigits:1})}</td><td>{r.missing?'—':r.total.toLocaleString(undefined,{maximumFractionDigits:1})}</td></tr>)}</tbody></table>{ingredients.some(i=>i.nutrition?.source)&&<details><summary>Nutrition sources and ingredient weights</summary><ul>{ingredients.map((i,n)=><li key={n}>{i.name}: {i.nutrition?.source||'Not matched'}{i.nutrition?.gramsPerUnit&&!mass[i.unit]?` · ${i.nutrition.gramsPerUnit} g per ${i.unit||'unit'}`:''}</li>)}</ul></details>}</section>;}
const blank=():Nutrition=>({source:'',gramsPerUnit:null,calories:null,protein:null,carbohydrates:null,fat:null,fiber:null,sugar:null,sodium:null});
type Food={id:string;description:string;brand:string;nutrition:Nutrition};
export function IngredientNutrition({ingredient,index,onChange}:{ingredient:Ingredient;index:number;onChange:(nutrition:Nutrition|null)=>void}){const [query,setQuery]=useState(ingredient.name),[foods,setFoods]=useState<Food[]>([]),[error,setError]=useState(''),[busy,setBusy]=useState(false);const n=ingredient.nutrition;
return <details className="ingredient-nutrition"><summary>Nutrition for ingredient {index+1}{n?' · source added':' · not added'}</summary><p>Match the exact food and brand, or enter values per 100 g from a reliable source. A cup needs this particular ingredient’s gram weight; we do not guess densities.</p><label>Food search {index+1}<input maxLength={120} value={query} onChange={e=>setQuery(e.target.value)}/></label><button type="button" disabled={busy||!query.trim()} onClick={async()=>{setBusy(true);setError('');setFoods([]);try{const found=await personalAPI<Food[]>('/foods/search','POST',{query});setFoods(found);if(!found.length)setError('No matches. Try another description or enter label values.');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}}>{busy?'Searching…':'Search USDA foods'}</button>{error&&<p role="alert">{error}</p>}{foods.length>0&&<ul className="food-matches">{foods.map(f=><li key={f.id}><button type="button" onClick={()=>{onChange({...f.nutrition,source:f.nutrition.source.slice(0,500)});setFoods([]);}}>{f.description}{f.brand?` · ${f.brand}`:''} · FDC {f.id}</button></li>)}</ul>}
{!n?<button type="button" onClick={()=>onChange(blank())}>Enter nutrition manually</button>:<><label>Nutrition source {index+1}<input required maxLength={500} value={n.source} onChange={e=>onChange({...n,source:e.target.value})} placeholder="Brand and package label, or food database reference"/></label>{!mass[ingredient.unit]&&<label>Grams per {ingredient.unit||'unit'} for ingredient {index+1}<input type="number" min="0.000001" max="100000" step="any" value={n.gramsPerUnit??''} onChange={e=>onChange({...n,gramsPerUnit:e.target.value===''?null:Number(e.target.value)})}/></label>}<p className="fine">All values below are per 100 g. For a label listing 30 g portions, multiply its nutrient values by 100 ÷ 30. Leave unknown values blank.</p><div className="form-grid">{nutrients.map(([key,label,unit])=><label key={key}>{label} ({unit}) per 100 g · ingredient {index+1}<input type="number" min="0" max="100000" step="any" value={n[key]??''} onChange={e=>onChange({...n,[key]:e.target.value===''?null:Number(e.target.value)})}/></label>)}</div><button type="button" onClick={()=>onChange(null)}>Clear nutrition source</button></>}</details>;
}
export const dietTags=['Non-GMO','Organic','Gluten-free','Lactose-free','Milk-free','Vegetarian','Vegan','Peanut-free','Tree-nut-free','Egg-free','Soy-free','Sesame-free','Fish-free','Shellfish-free'];
export function DietaryOptions({value,onChange}:{value:string;onChange:(s:string)=>void}){return <fieldset className="dietary-options"><legend>Dietary alternatives and ingredient preferences</legend><p className="fine">These are cook-entered labels, not verified allergy or certification claims. Check ingredient labels and cross-contact. Lactose-free is different from milk-free. Save changed ingredients as a variation and update their nutrition sources.</p><div className="dietary-tags">{dietTags.map(tag=><label key={tag}><input type="checkbox" checked={value.split('\n').includes(tag)} onChange={e=>onChange(e.target.checked?[...value.split('\n').filter(Boolean),tag].join('\n'):value.split('\n').filter(v=>v!==tag).join('\n'))}/>{tag}</label>)}</div></fieldset>;}
